### ISSUE TITLE
运行部了  vux报找不到

### ISSUE THREAD

**Issue by spiritelf** [consoles/vue-shop#10]

**Comment by consoles** [comment]
这个是6月份毕业的时候写的，基于vue1.0，vux的基于1。0版本的不再维护了。现在vue已经是2.0了。报错是路径的问题，已经修复，同时readme文档也已经更新了。

**Comment by spiritelf** [comment]
还继续维护 升级到2.0吗？

**Comment by consoles** [comment]
2.0的也很想尝试。只不过现在工作了，可能速度上会慢些。

**Comment by spiritelf** [comment]
_this.$broadcast('pullup:reset', uuid) 这个在新版本用什么替代啊？

**Comment by consoles** [comment]
参见[这个issue](https://github.com/webplus/blog/issues/10)吧，vue1.0有events属性，2.0的还不太熟悉。

**Comment by spiritelf** [comment]
vue.common.js?e881:1062Uncaught TypeError: Cannot read property 'NODE_ENV' of undefined(anonymous function) @ vue.common.js?e881:1062(anonymous function) @ app.js:594__webpack_require__ @ app.js:556fn @ app.js:87(anonymous function) @ main.js?3479:1(anonymous function) @ app.js:1346__webpack_require__ @ app.js:556fn @ app.js:87(anonymous function) @ app.js:587__webpack_require__ @ app.js:556(anonymous function) @ app.js:579(anonymous function) @ app.js:582

**Comment by consoles** [comment]
你是怎么运行的啊，我README中写的有啊，还有我的node版本是4.4.4

**Comment by spiritelf** [comment]
我的是5+ 直接 npm install  然后 npm run dev

**Comment by consoles** [comment]
特意安装了5.12.0，没有报错啊。
![npm run dev](https://cloud.githubusercontent.com/assets/12516428/22172092/82bea900-dfd9-11e6-90b3-f545a7d5c86c.png)

**Comment by spiritelf** [comment]
编译没报错。。运行的时候控制台报那个错

**Comment by consoles** [comment]
额，这个就不知道了。
