### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by shixin-guo** [consoles/vue-shop#11]
你好 我最近想了解一下node 和vue 觉得你这个源码很棒  想在本地跑一下  请问怎么运行  我现在npm install  之后只有前端代码运行  后端代码怎么启动  我在server的文件夹里面运行npm install 报错 。请问能告诉我怎么解决吗，

**Comment by consoles** [comment]
报错能贴出来吗

**Comment by shixin-guo** [comment]
好像是我开发环境的问题  你这个必须安装nginx 和redis环境吧

**Comment by consoles** [comment]
redis必须的，ngnix是可选的。

**Comment by shixin-guo** [comment]
ok  谢谢  我再试试 有问题可能还得麻烦你

**Comment by shixin-guo** [comment]
你好 我$ node server/bin/cluster.js之后报错 然后一直弹init express ，127.0.0.1也无法打开
报错截图
![image](https://cloud.githubusercontent.com/assets/12186221/22675674/0282856c-ed22-11e6-97dc-c952f6e4f87e.png)

我没有配置你的nginx。conf 因为你那个是直接替换掉默认的conf吧 我之前试过一次，路径有问题 我默认nginx安装在/etc/nginx/nginx.conf  我把你的conf替换 然后把里面的路径改成相对与我的工程下面 ，可是还是提示有文件未找到，这个未找到文件地址在conf中没有提到  

请问你知道怎么解决吗

**Comment by consoles** [comment]
一直init express应该是进程启动报错，导致无限重启，回头加个重试次数。看报错好像是qrcode这个模块没有安装好，你注释掉server/app/controllers/qrcode.js中的相关代码，node server/bin/cluster.js会在3000端口启动server，直接访问3000端口看看。

**Comment by shixin-guo** [comment]
我把qrcode的代码注释掉，还是报错，3000端口还是访问不了，，，，而且上面那个报错中提到的canvas也没有这个文件呀

![image](https://cloud.githubusercontent.com/assets/12186221/22676808/a7fe02cc-ed28-11e6-9186-d894a9d8fd8b.png)

**Comment by shixin-guo** [comment]
是不是我启动的姿势不对呀

**Comment by consoles** [comment]
使用npm info qrcode命令可以看到qrcode依赖canvas这个模块（这个模块需要编译C++）,server/app/controllers/qrcode.js改成这样：
```js
'use strict'

// const QRCode = require('qrcode')

module.exports = {
  qrcode: function(req,res,next){
    // let url = req.query.url
    // QRCode.toDataURL(url,function(err,data){
    //   if(err) throw Error(err)
    //   res.end(data)
    // })
    res.end('TODO')
  }
}
```

**Comment by shixin-guo** [comment]
![image](https://cloud.githubusercontent.com/assets/12186221/22677138/62d4afa4-ed2b-11e6-9f99-f5fad234a63b.png)

我觉的好像是好了   可是127.0.0.1无法访问 我在前端运行之后还是提示服务器出差了

**Comment by consoles** [comment]
这个只是api服务器，返回JSON，不渲染页面的，渲染逻辑交给vue.js,你看看http://127.0.0.1:3000/api/articles，应该可以得到数据。

**Comment by shixin-guo** [comment]
全是空数组  
![image](https://cloud.githubusercontent.com/assets/12186221/22677491/ef56e634-ed2d-11e6-9fdb-24e72c0c083e.png)
![image](https://cloud.githubusercontent.com/assets/12186221/22677528/2463b668-ed2e-11e6-9b4f-7d32b02010b7.png)

我运行了你的前端vue项目  npm run build 启动前端项目前端的部分正常运行  可是一到与服务器有关的 就失效  首页的下拉列表也没有反应然后注册失败
![image](https://cloud.githubusercontent.com/assets/12186221/22677505/0babd632-ed2e-11e6-97c1-ab0cdd607ed6.png)


我全部重新启动 从头来过  还是空数组

**Comment by consoles** [comment]
DB中有数据么，先要运行爬虫将数据抓取放入mongodb,注册的时候报什么错啊

**Comment by shixin-guo** [comment]
爬虫好使
![image](https://cloud.githubusercontent.com/assets/12186221/22677780/56a8c684-ed30-11e6-8e51-0e2c67794e7e.png)
注册没反应有验证码 点击之后就表单就空白了 而且没有邮件发送 （这个本地服务器也可以发送邮件吗）
![image](https://cloud.githubusercontent.com/assets/12186221/22677855/fd7ce9cc-ed30-11e6-82fd-8bc26ae40540.png)

再次链接127.0.0.1:3000/api/articles  还是空数组[{},{},{},{}] 304

![image](https://cloud.githubusercontent.com/assets/12186221/22678000/dc9508ce-ed31-11e6-9daf-166c610029ed.png)

**Comment by shixin-guo** [comment]
![image](https://cloud.githubusercontent.com/assets/12186221/22680765/c14ea382-ed44-11e6-809c-b5e37c2aedba.png)

请问这个需要我自己配置吗 用来验证什么的  是这个原因服务起链接不上吗

**Comment by consoles** [comment]
本地可以发啊，发送邮件需要配置自己的用户名和密码(server/config/config.js)，我的密码已经改了，用这个肯定没用的。server/config/ssl存放的是ssl证书，提供https（如果想使用http，修改nginx配置文件中的端口为80）。127.0.0.1:3000/api/articles原先是直接调用其他网站的api进行返回，现在http://app.xiaotaojiang.com/api-v2/articles失效了，请自己构造相关数据。还有，验证码功能其实是假的。

**Comment by shixin-guo** [comment]
谢谢，   真抱歉 麻烦你这么久  谢谢你的解答

**Comment by consoles** [comment]
😁没事，下午的时候开会去了。
